lab3/lab3/Models/BankInputModel.cs
using Lab3;
using System.ComponentModel;

namespace lab3.Models
{

    public class BankInputModel
    {
        [Description("Age")]
        [DisplayName("Age")]
        public int Age { get; set; }
        [Description("Job")]
        [DisplayName("Job")]
        public string Job { get; set; }
        [Description("Marital status")]
        [DisplayName("Marital")]
        public string Marital { get; set; }
        [Description("Education")]
        [DisplayName("Education")]
        public string Education { get; set; }
        [Description("Has credit in default?")]
        [DisplayName("Default")]
        public bool Default { get; set; }
        [Description("Average yearly balance(euro)")]
        [DisplayName("Balance")]
        public int Balance { get; set; }
        [Description("Has housing loan?")]
        [DisplayName("Housing")]
        public bool Housing { get; set; }
        [Description("Has personal loan?")]
        [DisplayName("Loan")]
        public bool Loan { get; set; }
        [Description("Contact communication type (cellular, telephone)")]
        [DisplayName("Contact")]
        public string Contact { get; set; }
        [Description("Last contact day of the week")]
        [DisplayName("Day")]
        public int Day { get; set; }
        [Description("Last contact month of year")]
        [DisplayName("Month")]
        public string Month { get; set; }
        [Description("last contact duration, in seconds")]
        [DisplayName("Duration")]
        public int Duration { get; set; }
        [Description("Number of contacts performed during this campaign and for this client")]
        [DisplayName("Campaign")]
        public int Campaign { get; set; }
        [Description("Number of days that passed by after the client was last contacted from a previous campaign")]
        [DisplayName("Pdays")]
        public int Pdays { get; set; }
        [Description("Number of contacts performed before this campaign and for this client")]
        [DisplayName("Previous")]
        public int Previous { get; set; }
        [Description("Outcome of the previous marketing campaign")]
        [DisplayName("Poutcome")]
        public string Poutcome { get; set; }
    }

    public class BankPredictionViewModel
    {
        public BankInputModel InputModel { get; set; }
        public BankMarketing.ModelOutput PredictionResult { get; set; }
    }
}

lab3/lab3/Models/ErrorViewModel.cs
namespace lab3.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

lab3/lab3/Controllers/BankController.cs
using lab3.Models;
using Lab3;
using Microsoft.AspNetCore.Mvc;

namespace lab3.Controllers
{
    public class BankController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Predict(BankInputModel inputModel)
        {
            var result = BankMarketing.Predict(new BankMarketing.ModelInput
            {
                Age = inputModel.Age,
                Job = inputModel.Job,
                Marital = inputModel.Marital,
                Education = inputModel.Education,
                Default = inputModel.Default,
                Balance = inputModel.Balance,
                Housing = inputModel.Housing,
                Loan = inputModel.Loan,
                Contact = inputModel.Contact,
                Day = inputModel.Day,
                Month = inputModel.Month,
                Duration = inputModel.Duration,
                Campaign = inputModel.Campaign,
                Pdays = inputModel.Pdays,
                Previous = inputModel.Previous,
                Poutcome = inputModel.Poutcome,
            });
            System.Diagnostics.Debug.WriteLine(inputModel.Age);
            var viewModel = new BankPredictionViewModel
            {
                InputModel = inputModel,
                PredictionResult = result
            };
            
            return View("~/Views/Home/Result.cshtml", viewModel);
        }
    }
}

lab3/lab3/Controllers/HomeController.cs
using lab3.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace lab3.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            System.Diagnostics.Debug.WriteLine("Hello");
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

lab3/lab3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model BankInputModel

@using (Html.BeginForm("Predict", "Bank", FormMethod.Post))
{
    @Html.Partial("_FormGroup", new Tuple<string, string> ("Age", "Age"))

    @Html.Partial("_FormGroup", new Tuple<string, string>("Job", "Job"))

    @Html.Partial("_FormGroup", new Tuple<string, string>("Marital", "Marital status"))

    @Html.Partial("_FormGroup", new Tuple<string, string>("Eduction", "Education"))

    @Html.Partial("_FormGroupCheckbox", new Tuple<string, string>("Default", "Has credit in default?"))

    @Html.Partial("_FormGroup", new Tuple<string, string>("Balance", "Average yearly balance(euro)"))

    @Html.Partial("_FormGroupCheckbox", new Tuple<string, string>("Housing", "Has housing loan?"))

    @Html.Partial("_FormGroupCheckbox", new Tuple<string, string>("Loan", "Has personal loan?"))

    @Html.Partial("_FormGroup", new Tuple<string, string>("Contact", "Contact communication type (cellular, telephone)"))

    @Html.Partial("_FormGroup", new Tuple<string, string>("Day", "Last contact day of the week"))

    @Html.Partial("_FormGroup", new Tuple<string, string>("Month", "Last contact month of year"))

    @Html.Partial("_FormGroup", new Tuple<string, string>("Duration", "Last contact duration, in seconds"))

    @Html.Partial("_FormGroup", new Tuple<string, string>("Campaign", "Number of contacts performed during this campaign and for this client"))

    @Html.Partial("_FormGroup", new Tuple<string, string>("Pdays", "Number of days that passed by after the client was last contacted from a previous campaign"))

    @Html.Partial("_FormGroup", new Tuple<string, string>("Previous", "Number of contacts performed before this campaign and for this client"))

    @Html.Partial("_FormGroup", new Tuple<string, string>("Poutcome", "Outcome of the previous marketing campaign"))

    <div class="form-group row mt-3">
        <div class="col-sm-10 offset-sm-2">
            <button type="submit" class="btn btn-primary">Predict</button>
        </div>
    </div>
}

lab3/lab3/Views/Home/Result.cshtml
@model BankPredictionViewModel

<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header bg-secondary text-white">
                    <h2 class="mb-0">Bank Prediction Result</h2>
                </div>
                <div class="card-body">
                    <h4 class="card-title">Result:</h4>
                    <p class="card-text">Has the client subscribed a term deposit? @(Model.PredictionResult.PredictedLabel ? "Yes" : "No")</p>
                </div>
            </div>
        </div>
    </div>
</div>

lab3/lab3/Views/Shared/_FormGroup.cshtml
@model Tuple<string, string> 

<div class="form-group row mt-3">
    <label for="@Model.Item1" class="col-sm-4 col-form-label">@Model.Item2:</label>
    <div class="col-sm-2">
        <input type="text" id="@Model.Item1" name="@Model.Item1" class="form-control bg-dark text-light" value="" />
    </div>
</div>

lab3/lab3/Views/Shared/_FormGroupCheckbox.cshtml
@model Tuple<string, string>

<div class="form-group row mt-3">
    <label for="@Model.Item1" class="col-sm-4 col-form-label">@Model.Item1:</label>
    <div class="col-sm-2">
        <div class="form-check">
            <input type="checkbox" id="@Model.Item1" name="@Model.Item1" class="form-check-input" value="" />
            <label class="form-check-label" for="@Model.Item1">@Model.Item2</label>
        </div>
    </div>
</div>

lab3/lab3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - lab3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lab3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">lab3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - lab3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>